name: MobiDL2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.8.2
  - pip==20.2.4
  - cromwell==53.1
  - samtools==1.10
  - bedtools==2.29.2
  - bcftools==1.10.2
  - bwa==0.7.17
  - crumble==0.8.3
  - dwgsim==1.1.11
  - fastqc==0.11.9
  - gatk4==4.1.8.1
  - sambamba==0.7.1
  - star==2.7.5c
  - qualimap==2.2.2d
  - bioconductor-repitools==1.34.0
  - cutadapt==2.10
  - ensembl-vep==101.0
  - vardict-java==1.8.2
  - wget==1.20.1
  - mobidic-mpa==1.1.2
  - regtools==0.6.0
  - rsync==3.1.3
  - snpeff==5.0
